### ISSUE TITLE
cannot find -lunitree_legged_sdk_amd64

### ISSUE THREAD

**Issue by HystericalHilb** [qiayuanliao/cheetah_ros#1]
Errors     << unitree_hw:make /home/hilb/Documents/catkin_ws/logs/unitree_hw/build.make.000.log                                                                                                                   
/usr/bin/ld: cannot find -lunitree_legged_sdk_amd64
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hilb/Documents/catkin_ws/devel/.private/unitree_hw/lib/unitree_hw/unitree_hw] Error 1
make[1]: *** [CMakeFiles/unitree_hw.dir/all] Error 2
make: *** [all] Error 2
cd /home/hilb/Documents/catkin_ws/build/unitree_hw; catkin build --get-env unitree_hw | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..................................................................................................................................................................................................................
Failed     << unitree_hw:make                          [ Exited with code 2 ]                                                                                                                                     
Failed    <<< unitree_hw                               [ 5.2 seconds ]                                                                                                                                            
Abandoned <<< cheetah_mpc_controllers                  [ Unrelated job failed ]

**Comment by qiayuanliao** [comment]
You need download [unitree_legged_sdk_amd64](https://github.com/unitreerobotics/unitree_legged_sdk). I will document it in the future.

**Comment by HystericalHilb** [comment]
thanks， actually I have installed the unitree_legged_sdk, it has a "lib" directory and I add&nbsp;libunitree_legged_sdk_amd64.so and&nbsp; libunitree_legged_sdk_arm64.so in env_var, but it's not ok
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiayuanliao/cheetah_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月19日(星期六) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qiayuanliao/cheetah_ros] cannot find -lunitree_legged_sdk_amd64 (Issue #1)





 
You need download unitree_legged_sdk_amd64. I will document it in the future.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiayuanliao** [comment]
You should copy the unitree_legged_sdk into the unitree_ros/lib directly

**Comment by HystericalHilb** [comment]
you mean that I should install the unitree_ros. I will write the way I build your code, and I hope you can get the file how to install and build. thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiayuanliao/cheetah_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 凌晨0:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qiayuanliao/cheetah_ros] cannot find -lunitree_legged_sdk_amd64 (Issue #1)





 
You should copy the unitree_legged_sdk into the unitree_ros/lib directly
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiayuanliao** [comment]
> you mean that I should install the unitree_ros

Unitree's official `unitree_ros` don't have an "install" option. So I'm not quite sure what installation you are referring to?
My file tree of unitree_hw is shown below. Hope it helps you.

```
unitree_hw
├── CMakeLists.txt
├── config
│   └── default.yaml
├── include
│   ├── unitree_hw
│   │   ├── control_loop.h
│   │   └── hardware_interface.h
│   └── unitree_legged_sdk
│       ├── comm.h
│       ├── quadruped.h
│       ├── safety.h
│       └── udp.h
├── launch
│   └── unitree_hw.launch
├── lib
│   └── libunitree_legged_sdk_amd64.so
├── package.xml
└── src
    ├── control_loop.cpp
    ├── hardware_interface.cpp
    └── unitree_hw.cpp
```

**Comment by HystericalHilb** [comment]
I copy the&nbsp;libunitree_legged_sdk_amd64.so into the lib dir, it does work. but I meet the problems as following here
I think it's the c++ and ros version... , i use the ros-melodic in ubuntu18







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiayuanliao/cheetah_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qiayuanliao/cheetah_ros] cannot find -lunitree_legged_sdk_amd64 (Issue #1)





  
you mean that I should install the unitree_ros
  
Unitree's official unitree_ros don't have an "install" option. So I'm not quite sure what installation you are referring to?
 My file tree of unitree_hw is shown below. Hope it helps you.
 unitree_hw ├── CMakeLists.txt ├── config │&nbsp;&nbsp; └── default.yaml ├── include │&nbsp;&nbsp; ├── unitree_hw │&nbsp;&nbsp; │&nbsp;&nbsp; ├── control_loop.h │&nbsp;&nbsp; │&nbsp;&nbsp; └── hardware_interface.h │&nbsp;&nbsp; └── unitree_legged_sdk │&nbsp;&nbsp;     ├── comm.h │&nbsp;&nbsp;     ├── quadruped.h │&nbsp;&nbsp;     ├── safety.h │&nbsp;&nbsp;     └── udp.h ├── launch │&nbsp;&nbsp; └── unitree_hw.launch ├── lib │&nbsp;&nbsp; └── libunitree_legged_sdk_amd64.so ├── package.xml └── src     ├── control_loop.cpp     ├── hardware_interface.cpp     └── unitree_hw.cpp  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HystericalHilb** [comment]
Now I meet this problem, I tried to address it, but not fine


Scanning dependencies of target cheetah_mpc_controllers
[ 85%] Building CXX object cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/src/mpc_formulation.cpp.o
[ 89%] Building CXX object cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/src/mpc_controller.cpp.o
[ 89%] Building CXX object cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/src/locomotion.cpp.o
[ 91%] Linking CXX shared library /home/regins/Documents/catkin_ws/devel/lib/libcheetah_mpc_controllers.so
/usr/bin/ld: /opt/ros/noetic/lib/libqpOASES.a(QProblem.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK7qpOASES8QProblem5getNZEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/build.make:148: /home/regins/Documents/catkin_ws/devel/lib/libcheetah_mpc_controllers.so] Error 1





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiayuanliao/cheetah_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qiayuanliao/cheetah_ros] cannot find -lunitree_legged_sdk_amd64 (Issue #1)





  
you mean that I should install the unitree_ros
  
Unitree's official unitree_ros don't have an "install" option. So I'm not quite sure what installation you are referring to?
 My file tree of unitree_hw is shown below. Hope it helps you.
 unitree_hw ├── CMakeLists.txt ├── config │&nbsp;&nbsp; └── default.yaml ├── include │&nbsp;&nbsp; ├── unitree_hw │&nbsp;&nbsp; │&nbsp;&nbsp; ├── control_loop.h │&nbsp;&nbsp; │&nbsp;&nbsp; └── hardware_interface.h │&nbsp;&nbsp; └── unitree_legged_sdk │&nbsp;&nbsp;     ├── comm.h │&nbsp;&nbsp;     ├── quadruped.h │&nbsp;&nbsp;     ├── safety.h │&nbsp;&nbsp;     └── udp.h ├── launch │&nbsp;&nbsp; └── unitree_hw.launch ├── lib │&nbsp;&nbsp; └── libunitree_legged_sdk_amd64.so ├── package.xml └── src     ├── control_loop.cpp     ├── hardware_interface.cpp     └── unitree_hw.cpp  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HystericalHilb** [comment]
I address this with compiling the qpQASES and adding "add_compile_options(-fPIC)". then, I put the "libqpOASES.a" into /opt/ros/neotic/lib




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "起床困难户"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 晚上7:54
***@***.***&gt;;

主题:&nbsp;回复： [qiayuanliao/cheetah_ros] cannot find -lunitree_legged_sdk_amd64 (Issue #1)





Now I meet this problem, I tried to address it, but not fine


Scanning dependencies of target cheetah_mpc_controllers
[ 85%] Building CXX object cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/src/mpc_formulation.cpp.o
[ 89%] Building CXX object cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/src/mpc_controller.cpp.o
[ 89%] Building CXX object cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/src/locomotion.cpp.o
[ 91%] Linking CXX shared library /home/regins/Documents/catkin_ws/devel/lib/libcheetah_mpc_controllers.so
/usr/bin/ld: /opt/ros/noetic/lib/libqpOASES.a(QProblem.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK7qpOASES8QProblem5getNZEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [cheetah_ros/cheetah_mpc_controllers/CMakeFiles/cheetah_mpc_controllers.dir/build.make:148: /home/regins/Documents/catkin_ws/devel/lib/libcheetah_mpc_controllers.so] Error 1





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "qiayuanliao/cheetah_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qiayuanliao/cheetah_ros] cannot find -lunitree_legged_sdk_amd64 (Issue #1)





  
you mean that I should install the unitree_ros
  
Unitree's official unitree_ros don't have an "install" option. So I'm not quite sure what installation you are referring to?
 My file tree of unitree_hw is shown below. Hope it helps you.
 unitree_hw ├── CMakeLists.txt ├── config │ &nbsp; └── default.yaml ├── include │ &nbsp; ├── unitree_hw │ &nbsp; │ &nbsp; ├── control_loop.h │ &nbsp; │ &nbsp; └── hardware_interface.h │ &nbsp; └── unitree_legged_sdk │ &nbsp;     ├── comm.h │ &nbsp;     ├── quadruped.h │ &nbsp;     ├── safety.h │ &nbsp;     └── udp.h ├── launch │ &nbsp; └── unitree_hw.launch ├── lib │ &nbsp; └── libunitree_legged_sdk_amd64.so ├── package.xml └── src     ├── control_loop.cpp     ├── hardware_interface.cpp     └── unitree_hw.cpp  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiayuanliao** [comment]
The `qpQASES` now is added as `qpoases_catkin` package, and will be automatically downloaded while loading CMakeList

**Comment by qiayuanliao** [comment]
> 

The v3.3.1 libunitree_legged_sdk_amd64 is uploaded.

**Comment by qiayuanliao** [comment]
This repository is about to be archived, I will rewrite the code with ocs2.
