### ISSUE TITLE
MPC controller can't stand

### ISSUE THREAD

**Issue by skywoodsz** [qiayuanliao/cheetah_ros#2]
Hi, I ues the demo launch file located in the path "cheetah_mpc_controller/launch". But I find the mpc controller can't control the dog to stand. And when I start the mpc controller, my gazebo real time factor decreases from 1.0 to 0.20. 

My system is ubuntu 20.04,  i7-8700 cpu and GTX1050. I don't know how to fix this problem. Could you give me some advices? Thanks!

![Uploading 2022-06-09_22-57.png…]()
![Uploading 2022-06-09_22-57.png…]()

**Comment by qiayuanliao** [comment]
I can't see the figures.
This repo is archived. For the latest work about legged robot control, please refer to the [legged_control](https://github.com/qiayuanliao/legged_control).
